# Profile information
#
name: Mathy Bit
title: The Mathy Bit
author: Adrian Pacurar
description: > # this means to ignore newlines until "baseurl:"
  math, cryptography, number theory, graph theory, combinatorics, machine learning, artificial intelligence, neural networks
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mathybit.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

google-analytics: "UA-124634802-1"
textlogo: logo1.png


# Social Media
#
#facebook: #Add your Facebook
#twitter: #Add your Twitter
#google-plus: #Add your Google+
instagram: cosmipics
linkedin: adi-pacurar
github: mathybit


# Contact form
#
email: writetoadriano@gmail.com


# Comments
#
#discus-identifier: # Add your Disqus identifier


# Paginate
#
paginate: 5
paginate_path: /page:num/


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
